version: '2'
services:
  dockvpn:
    build: ./DockVPN
    image: dockvpn
    privileged: true
    ports:
      - "443:443"
      - "1194:1194"
  serveconfig:
    build: ./DockVPN
    image: dockvpn
    depends_on:
      - dockvpn
    volumes_from:
      - dockvpn
    links:
      - dockvpn
    entrypoint: serveconfig
  config-ui:
    build: ./UI
    image: vpn-config-ui
    links: 
      - dockvpn
      - serveconfig
    depends_on:
      - dockvpn
    ports:
      - "10889:4567"


